#!/usr/bin/env python3
"""Genere src/js2e.js : la base d'aliments de base (onglet « Chercher » du Repas).

    python3 tools/gen_aliments.py

Valeurs MOYENNES pour 100 g (ou 100 ml pour les boissons) : calories, proteines,
glucides, lipides. Ce sont des ordres de grandeur d'aliments non transformes,
ecrits pour l'application d'apres les valeurs usuelles des tables nutritionnelles ;
ils different d'une marque ou d'un mode de cuisson a l'autre. Un produit de
marque se scanne ; ceci sert pour les aliments « sans code-barres » (oeuf, riz...).
Rien n'est recopie d'une base de donnees : ce sont des faits courants, saisis ici.

Chaque aliment : categorie, nom, kcal, P, G, L, unites usuelles, options, alias.
  categorie : « section.sous-section », la MEME classification que la bibliotheque du Scan
              (SLIB dans src/js4b.js) : vpo.viande, lait.yaourt, fl.fruits, plat.pizza...
  unites : (libelle 'singulier|pluriel', grammes, mode)
           mode 's' : le libelle EST l'aliment  -> « 2 oeufs »
           mode 'd' : le libelle contient l'aliment -> « 2 tranches de pain complet »
  options : 'ml' (boisson, en ml) ; top=N (affiche dans « Courants », rang N)
  alias : mots de recherche en plus du nom (sans importance pour les accents).

Pour ajouter un aliment : une ligne dans TABLE, relancer, puis ./src/build.sh.
"""
import json, os, re, unicodedata

TABLE = []
# Rangements valides : a garder identiques a SLIB (src/js4b.js). tests/t11.py le verifie.
VALID = set('''vpo.viande vpo.charcut vpo.poisson vpo.oeuf lait.lait lait.yaourt lait.fromage lait.creme
fl.fruits fl.legumes fl.secs fec.pain fec.pates fec.cereales fec.legumineuses
sucre.biscuit sucre.choco sucre.tartiner sucre.dessert sucre.sucre gras.huile gras.sauce
boisson.eau boisson.jus boisson.veg boisson.cafe boisson.alcool plat.plat plat.pizza plat.sandwich plat.soupe
snack.chips snack.barre sport.whey sport.boisson sport.barre autre.autre'''.split())
def F(cat, nom, k, p, c, f, u=(), ml=False, top=0, a=''):
    TABLE.append(dict(cat=cat, n=nom, k=k, p=p, c=c, f=f, u=list(u), ml=ml, top=top, a=a))

PORTION = ('portion|portions', 150, 'd')

# ---------------------------------------------------------------- oeufs et laitiers
F('vpo.oeuf', 'Œuf entier', 143, 12.7, 0.7, 9.8, [('œuf|œufs', 55, 's')], top=1, a='oeuf poule dur brouille omelette plat poche')
F('vpo.oeuf', 'Blanc d’œuf', 47, 10.5, 0.7, 0.2, [('blanc d’œuf|blancs d’œuf', 33, 's')], top=20, a='oeuf')
F('vpo.oeuf', 'Jaune d’œuf', 322, 16, 3.6, 26.5, [('jaune d’œuf|jaunes d’œuf', 18, 's')], a='oeuf')
F('lait.lait', 'Lait demi-écrémé', 46, 3.2, 4.8, 1.6, [('verre|verres', 200, 'd'), ('bol|bols', 250, 'd')], ml=True, top=2)
F('lait.lait', 'Lait écrémé', 33, 3.4, 4.8, 0.1, [('verre|verres', 200, 'd'), ('bol|bols', 250, 'd')], ml=True)
F('lait.lait', 'Lait entier', 64, 3.3, 4.7, 3.6, [('verre|verres', 200, 'd'), ('bol|bols', 250, 'd')], ml=True)
F('boisson.veg', 'Lait d’amande sans sucre', 15, 0.5, 0.3, 1.1, [('verre|verres', 200, 'd')], ml=True, a='boisson amande vegetal')
F('boisson.veg', 'Lait de soja nature', 40, 3.3, 2.5, 1.8, [('verre|verres', 200, 'd')], ml=True, a='boisson soja vegetal')
F('boisson.veg', 'Boisson à l’avoine', 45, 0.5, 6.5, 1.5, [('verre|verres', 200, 'd')], ml=True, a='lait avoine vegetal')
F('lait.yaourt', 'Yaourt nature', 55, 4.2, 5.5, 1.8, [('pot|pots', 125, 'd')], a='yogourt yoghourt')
F('lait.yaourt', 'Yaourt grec 0 %', 55, 9.5, 4, 0.3, [('pot|pots', 150, 'd')], top=3, a='yogourt yoghourt nature maigre')
F('lait.yaourt', 'Yaourt grec entier', 115, 5, 4, 8.5, [('pot|pots', 150, 'd')], a='yogourt yoghourt')
F('lait.yaourt', 'Fromage blanc 0 %', 46, 7.5, 4, 0.2, [('pot|pots', 100, 'd')], top=4, a='faisselle maigre')
F('lait.yaourt', 'Fromage blanc 3 %', 75, 7.5, 4, 3.2, [('pot|pots', 100, 'd')])
F('lait.yaourt', 'Skyr nature', 62, 11, 4, 0.2, [('pot|pots', 140, 'd')], top=5, a='yaourt islandais')
F('lait.yaourt', 'Cottage cheese', 98, 11, 3.4, 4.3, [], a='fromage frais granule')
F('lait.fromage', 'Mozzarella', 250, 18, 1, 19, [('boule|boules', 125, 'd')])
F('lait.fromage', 'Mozzarella allégée', 165, 20, 1, 8.5, [('boule|boules', 125, 'd')], a='light')
F('lait.fromage', 'Emmental râpé', 380, 28, 0.5, 29, [('càs', 7, 'd')], a='fromage rape gruyere')
F('lait.fromage', 'Comté', 410, 27, 0.5, 34, [('tranche|tranches', 20, 'd')], a='fromage')
F('lait.fromage', 'Parmesan', 400, 35, 0, 28, [('càs', 7, 'd')], a='fromage rape grana')
F('lait.fromage', 'Feta', 260, 14, 1, 21, [], a='fromage grec')
F('lait.fromage', 'Camembert', 270, 20, 0.5, 21, [('part|parts', 30, 'd')], a='fromage brie')
F('lait.creme', 'Beurre', 740, 0.7, 0.6, 82, [('càc', 5, 'd'), ('noix|noix', 10, 'd')], a='matiere grasse')
F('lait.creme', 'Crème fraîche épaisse 30 %', 300, 2.2, 2.6, 30, [('càs', 15, 'd')])
F('lait.creme', 'Crème fraîche légère 15 %', 155, 2.8, 3.8, 15, [('càs', 15, 'd')])

# ---------------------------------------------------------------- viandes
F('vpo.viande', 'Blanc de poulet cru', 110, 23, 0, 1.3, [], top=6, a='filet escalope volaille')
F('vpo.viande', 'Blanc de poulet cuit', 165, 31, 0, 3.6, [], top=7, a='filet escalope volaille')
F('vpo.viande', 'Cuisse de poulet sans peau cuite', 190, 27, 0, 9, [], a='volaille')
F('vpo.viande', 'Escalope de dinde crue', 105, 24, 0, 1, [], a='blanc filet volaille')
F('vpo.viande', 'Blanc de dinde cuit', 150, 30, 0, 2.5, [], a='escalope filet volaille')
F('vpo.viande', 'Dinde hachée 5 % crue', 130, 20, 0, 5.5, [], a='steak hache volaille')
F('vpo.viande', 'Bœuf haché 5 % cru', 125, 21, 0, 5, [], top=8, a='boeuf steak hache viande')
F('vpo.viande', 'Bœuf haché 15 % cru', 215, 18, 0, 15, [], a='boeuf steak hache viande')
F('vpo.viande', 'Steak haché 5 % cuit', 170, 27, 0, 6.5, [], a='boeuf hache viande')
F('vpo.viande', 'Bœuf cuit (rumsteck, steak)', 190, 28, 0, 8, [], a='boeuf viande rouge')
F('vpo.viande', 'Filet mignon de porc cru', 120, 21, 0, 4, [], a='porc viande')
F('vpo.viande', 'Escalope de veau cuite', 175, 29, 0, 6, [], a='viande')
F('vpo.charcut', 'Jambon blanc', 105, 20, 0.5, 2.5, [('tranche|tranches', 45, 'd')], top=9, a='jambon decouenne porc charcuterie')
F('vpo.charcut', 'Jambon cru', 235, 27, 0.3, 14, [('tranche|tranches', 20, 'd')], a='charcuterie jambon sec serrano parme')
F('vpo.charcut', 'Viande des Grisons', 150, 32, 0.5, 2.5, [('tranche|tranches', 15, 'd')], a='bresaola charcuterie boeuf seche')
F('vpo.charcut', 'Lardons fumés', 270, 17, 0.5, 22, [], a='bacon poitrine porc')
F('vpo.charcut', 'Saucisse de Strasbourg', 260, 12, 2, 23, [('saucisse|saucisses', 50, 's')], a='knack')
F('vpo.charcut', 'Chipolata', 290, 14, 1, 25, [('chipolata|chipolatas', 50, 's')], a='saucisse porc')

# ---------------------------------------------------------------- poissons
F('vpo.poisson', 'Saumon cru', 200, 20, 0, 13, [('pavé|pavés', 130, 'd')], a='poisson pave filet')
F('vpo.poisson', 'Saumon cuit', 215, 24, 0, 13, [('pavé|pavés', 110, 'd')], top=10, a='poisson pave filet')
F('vpo.poisson', 'Saumon fumé', 185, 22, 0, 11, [('tranche|tranches', 30, 'd')], a='poisson')
F('vpo.poisson', 'Cabillaud cru', 80, 18, 0, 0.7, [('pavé|pavés', 150, 'd')], a='poisson dos morue')
F('vpo.poisson', 'Cabillaud cuit', 105, 23, 0, 1, [('pavé|pavés', 120, 'd')], a='poisson dos morue')
F('vpo.poisson', 'Colin ou lieu cru', 75, 17, 0, 0.7, [('filet|filets', 120, 'd')], a='poisson merlu')
F('vpo.poisson', 'Thon au naturel (égoutté)', 110, 25, 0, 1, [('boîte|boîtes', 110, 'd')], top=11, a='poisson conserve')
F('vpo.poisson', 'Thon à l’huile (égoutté)', 190, 26, 0, 9, [('boîte|boîtes', 110, 'd')], a='poisson conserve')
F('vpo.poisson', 'Sardines à l’huile (égouttées)', 210, 24, 0, 12, [('boîte|boîtes', 90, 'd')], a='poisson conserve')
F('vpo.poisson', 'Crevettes cuites', 90, 19, 0.5, 1, [], a='fruits de mer decortiquees')
F('vpo.poisson', 'Surimi', 90, 8, 9, 1, [('bâtonnet|bâtonnets', 15, 'd')], a='baton crabe')

# ---------------------------------------------------------------- feculents et legumineuses
F('fec.pates', 'Riz basmati cuit', 130, 2.7, 28, 0.3, [PORTION], top=12, a='riz blanc')
F('fec.pates', 'Riz complet cuit', 125, 2.7, 26, 1, [PORTION])
F('fec.pates', 'Riz cru', 350, 8, 77, 0.8, [], a='riz basmati blanc')
F('fec.pates', 'Pâtes cuites', 155, 5.4, 31, 0.7, [PORTION], top=13, a='spaghetti tagliatelles penne coquillettes')
F('fec.pates', 'Pâtes crues', 355, 12.5, 72, 1.5, [], a='spaghetti tagliatelles penne coquillettes')
F('fec.pates', 'Pâtes complètes cuites', 150, 6, 28, 1.1, [PORTION], a='spaghetti')
F('fec.pates', 'Semoule ou couscous cuit', 112, 3.8, 23, 0.2, [PORTION])
F('fec.pates', 'Quinoa cuit', 120, 4.4, 21, 1.9, [PORTION])
F('fec.pates', 'Quinoa cru', 360, 14, 64, 6, [])
F('fec.pates', 'Boulgour cru', 340, 12, 64, 1.5, [])
F('fl.legumes', 'Pommes de terre cuites', 80, 2, 17, 0.1, [('pomme de terre|pommes de terre', 120, 's')], top=14, a='patate vapeur eau')
F('fl.legumes', 'Pommes de terre crues', 77, 2, 17, 0.1, [('pomme de terre|pommes de terre', 150, 's')], a='patate')
F('fl.legumes', 'Patate douce cuite', 90, 2, 20.5, 0.1, [], a='pdt')
F('fec.cereales', 'Flocons d’avoine', 372, 13.5, 59, 7, [('càs', 10, 'd'), ('bol|bols', 40, 'd')], top=15, a='porridge cereales petit dejeuner')
F('fec.cereales', 'Corn flakes', 375, 7, 84, 0.9, [('bol|bols', 40, 'd')], a='cereales petit dejeuner')
F('fec.cereales', 'Granola', 440, 9, 64, 16, [('bol|bols', 50, 'd')], a='cereales muesli petit dejeuner')
F('fec.pain', 'Pain blanc (baguette)', 275, 9, 57, 1.2, [('tranche|tranches', 30, 'd'), ('morceau|morceaux', 60, 'd')], a='baguette')
F('fec.pain', 'Pain complet', 250, 9, 44, 3, [('tranche|tranches', 35, 'd')], top=16)
F('fec.pain', 'Pain de mie complet', 255, 9, 43, 4, [('tranche|tranches', 28, 'd')], a='tranche')
F('fec.pain', 'Pain de mie nature', 270, 8, 50, 4, [('tranche|tranches', 28, 'd')], a='tranche')
F('fec.pain', 'Pain à burger', 270, 9, 48, 4, [('pain à burger|pains à burger', 60, 's')], a='bun')
F('fec.pain', 'Wrap (tortilla de blé)', 300, 8, 50, 7, [('wrap|wraps', 60, 's')], a='galette tortilla fajita')
F('fec.pain', 'Biscottes', 390, 11, 73, 5, [('biscotte|biscottes', 8, 's')])
F('fec.pain', 'Galette de riz soufflée', 380, 8, 80, 2.5, [('galette de riz|galettes de riz', 9, 's')])
F('fec.legumineuses', 'Lentilles cuites', 110, 8.5, 16.5, 0.5, [PORTION], a='legumineuse lentille verte')
F('fec.legumineuses', 'Lentilles corail (crues)', 340, 24, 50, 1.5, [], a='legumineuse lentille')
F('fec.legumineuses', 'Pois chiches cuits (égouttés)', 125, 8.5, 17, 2.6, [], a='legumineuse conserve')
F('fec.legumineuses', 'Haricots rouges cuits (égouttés)', 110, 8, 15, 0.5, [], a='legumineuse conserve')
F('fec.legumineuses', 'Haricots blancs cuits (égouttés)', 105, 7, 15, 0.6, [], a='legumineuse conserve')
F('fec.legumineuses', 'Tofu ferme', 120, 13, 2, 7, [], a='soja vegetal proteine')
F('fec.legumineuses', 'Tempeh', 195, 19, 9, 11, [], a='soja vegetal proteine')
F('fec.legumineuses', 'Houmous', 230, 7, 14, 16, [('càs', 15, 'd')], a='hummus pois chiches')

# ---------------------------------------------------------------- legumes
F('fl.legumes', 'Tomate', 18, 0.9, 3.5, 0.2, [('tomate|tomates', 120, 's')], top=17)
F('fl.legumes', 'Tomate cerise', 18, 0.9, 3.5, 0.2, [('tomate cerise|tomates cerises', 15, 's')])
F('fl.legumes', 'Concombre', 12, 0.6, 2, 0.1, [])
F('fl.legumes', 'Courgette', 17, 1.2, 2.5, 0.3, [])
F('fl.legumes', 'Carotte', 36, 0.8, 7, 0.2, [('carotte|carottes', 80, 's')])
F('fl.legumes', 'Brocoli', 34, 2.8, 4, 0.4, [], a='chou')
F('fl.legumes', 'Chou-fleur', 25, 2, 3, 0.3, [])
F('fl.legumes', 'Épinards', 23, 2.9, 1.5, 0.4, [], a='epinard')
F('fl.legumes', 'Haricots verts cuits', 30, 2, 4, 0.2, [], a='haricot vert')
F('fl.legumes', 'Poivron', 28, 1, 6, 0.3, [('poivron|poivrons', 150, 's')])
F('fl.legumes', 'Oignon', 40, 1.1, 8, 0.1, [('oignon|oignons', 80, 's')])
F('fl.legumes', 'Champignons de Paris', 22, 3, 1, 0.3, [])
F('fl.legumes', 'Aubergine cuite', 25, 1, 3.5, 0.3, [])
F('fl.legumes', 'Salade verte', 15, 1.3, 1.5, 0.2, [], a='laitue batavia mache')
F('fl.legumes', 'Roquette', 25, 2.6, 2.1, 0.7, [], a='salade')
F('fl.legumes', 'Maïs en conserve', 90, 3, 15, 1.5, [], a='mais')
F('fl.legumes', 'Petits pois', 80, 5.5, 10, 0.5, [], a='petit pois conserve cuits')
F('fl.legumes', 'Avocat', 160, 2, 2, 15, [('avocat|avocats', 120, 's')], a='guacamole')
F('fl.legumes', 'Courge butternut cuite', 40, 1, 8, 0.1, [], a='potimarron potiron')
F('fl.legumes', 'Betterave cuite', 45, 1.7, 8.5, 0.2, [])
F('fl.legumes', 'Chou rouge ou blanc', 25, 1.4, 4, 0.2, [])
F('fl.legumes', 'Radis', 15, 0.7, 2, 0.1, [])
F('fl.legumes', 'Asperges', 22, 2.2, 2, 0.2, [])

# ---------------------------------------------------------------- fruits
F('fl.fruits', 'Banane', 90, 1.1, 20, 0.3, [('banane|bananes', 100, 's')], top=18)
F('fl.fruits', 'Pomme', 52, 0.3, 12, 0.2, [('pomme|pommes', 150, 's')], top=19)
F('fl.fruits', 'Poire', 55, 0.4, 12, 0.2, [('poire|poires', 150, 's')])
F('fl.fruits', 'Orange', 47, 0.9, 10, 0.2, [('orange|oranges', 150, 's')])
F('fl.fruits', 'Clémentine', 47, 0.8, 10, 0.2, [('clémentine|clémentines', 70, 's')], a='mandarine')
F('fl.fruits', 'Kiwi', 55, 1.1, 11, 0.5, [('kiwi|kiwis', 70, 's')])
F('fl.fruits', 'Fraises', 33, 0.7, 6, 0.3, [], a='fraise')
F('fl.fruits', 'Framboises', 45, 1.2, 6.5, 0.5, [], a='framboise')
F('fl.fruits', 'Myrtilles', 50, 0.7, 10, 0.3, [], a='myrtille bleuets')
F('fl.fruits', 'Fruits rouges (mélange)', 45, 0.7, 9, 0.3, [], a='fruit rouge surgeles')
F('fl.fruits', 'Raisin', 70, 0.7, 16, 0.2, [])
F('fl.fruits', 'Mangue', 60, 0.8, 13.5, 0.4, [])
F('fl.fruits', 'Ananas', 50, 0.5, 11, 0.1, [])
F('fl.fruits', 'Pêche', 40, 0.9, 8, 0.2, [('pêche|pêches', 150, 's')], a='peche nectarine')
F('fl.fruits', 'Abricot', 45, 0.9, 9, 0.1, [('abricot|abricots', 45, 's')])
F('fl.fruits', 'Pastèque', 30, 0.6, 7, 0.2, [], a='pasteque')
F('fl.fruits', 'Melon', 34, 0.8, 7.5, 0.2, [])
F('fl.fruits', 'Cerises', 60, 1, 13, 0.3, [], a='cerise')
F('fl.fruits', 'Compote sans sucre ajouté', 45, 0.4, 10, 0.1, [('pot|pots', 100, 'd'), ('gourde|gourdes', 90, 'd')], a='pomme')
F('fl.secs', 'Raisins secs', 300, 3, 70, 0.5, [], a='fruit sec')
F('fl.secs', 'Datte', 280, 2, 70, 0.2, [('datte|dattes', 25, 's')], a='fruit sec medjool')
F('boisson.jus', 'Jus d’orange', 45, 0.7, 10, 0.2, [('verre|verres', 200, 'd')], ml=True, a='boisson')
F('boisson.jus', 'Jus de pomme', 46, 0.1, 11, 0.1, [('verre|verres', 200, 'd')], ml=True, a='boisson')

# ---------------------------------------------------------------- gras, noix, sucre
F('gras.huile', 'Huile d’olive', 900, 0, 0, 100, [('càs', 13, 'd'), ('càc', 5, 'd')], top=21, a='matiere grasse')
F('gras.huile', 'Huile de colza', 900, 0, 0, 100, [('càs', 13, 'd'), ('càc', 5, 'd')], a='matiere grasse')
F('gras.sauce', 'Mayonnaise', 690, 1, 1.5, 76, [('càs', 15, 'd')], a='sauce')
F('gras.sauce', 'Ketchup', 100, 1, 24, 0.1, [('càs', 17, 'd')], a='sauce tomate')
F('gras.sauce', 'Moutarde', 100, 5.5, 5, 6, [('càc', 5, 'd')], a='sauce')
F('fl.secs', 'Amandes', 600, 21, 7, 53, [('poignée|poignées', 25, 'd')], top=22, a='amande oleagineux fruits a coque')
F('fl.secs', 'Noix', 670, 15, 7, 65, [('poignée|poignées', 25, 'd')], a='oleagineux fruits a coque cerneaux')
F('fl.secs', 'Noix de cajou', 590, 18, 27, 46, [('poignée|poignées', 25, 'd')], a='cajou oleagineux fruits a coque')
F('fl.secs', 'Cacahuètes (non salées)', 590, 26, 9, 50, [('poignée|poignées', 25, 'd')], a='cacahuete arachide oleagineux')
F('fl.secs', 'Pistaches', 590, 20, 17, 50, [('poignée|poignées', 25, 'd')], a='oleagineux fruits a coque')
F('fl.secs', 'Noisettes', 650, 15, 7, 61, [('poignée|poignées', 25, 'd')], a='oleagineux fruits a coque')
F('fl.secs', 'Graines de chia', 486, 16.5, 8, 31, [('càs', 12, 'd')], a='graine')
F('sucre.tartiner', 'Beurre de cacahuète', 600, 26, 12, 50, [('càs', 16, 'd'), ('càc', 5, 'd')], top=23, a='cacahuete peanut butter')
F('sucre.tartiner', 'Pâte à tartiner chocolat-noisette', 540, 6, 57, 31, [('càc', 8, 'd'), ('càs', 20, 'd')], a='nutella')
F('sucre.choco', 'Chocolat noir 70 %', 560, 8, 35, 40, [('carré|carrés', 8, 'd')], a='carre')
F('sucre.choco', 'Chocolat au lait', 550, 7, 57, 32, [('carré|carrés', 8, 'd')], a='carre')
F('sucre.tartiner', 'Miel', 300, 0.3, 75, 0, [('càc', 7, 'd'), ('càs', 20, 'd')])
F('sucre.sucre', 'Sucre', 400, 0, 100, 0, [('morceau|morceaux', 6, 'd'), ('càc', 5, 'd')])
F('sucre.tartiner', 'Confiture', 250, 0.4, 60, 0.1, [('càs', 20, 'd')])
F('sucre.sucre', 'Sirop d’érable', 260, 0, 67, 0, [('càs', 20, 'd')], a='erable')

# ---------------------------------------------------------------- boissons
F('boisson.cafe', 'Café noir sans sucre', 2, 0.2, 0, 0, [('tasse|tasses', 150, 'd')], ml=True, a='expresso')
F('boisson.cafe', 'Thé ou infusion sans sucre', 1, 0, 0.2, 0, [('tasse|tasses', 200, 'd')], ml=True, a='the')
F('boisson.jus', 'Soda au cola', 42, 0, 10.6, 0, [('canette|canettes', 330, 'd'), ('verre|verres', 200, 'd')], ml=True, a='coca cola pepsi')
F('boisson.jus', 'Soda au cola zéro', 0, 0, 0, 0, [('canette|canettes', 330, 'd')], ml=True, a='coca cola zero light')
F('boisson.alcool', 'Bière', 43, 0.4, 3.5, 0, [('demi|demis', 250, 'd'), ('canette|canettes', 330, 'd')], ml=True, a='biere alcool')
F('boisson.alcool', 'Vin rouge ou blanc', 70, 0.1, 0.5, 0, [('verre|verres', 125, 'd')], ml=True, a='alcool')

# ---------------------------------------------------------------- autres
F('sport.whey', 'Whey (protéine en poudre)', 400, 80, 7, 5, [('dose|doses', 30, 'd')], top=24, a='proteine shaker poudre')
F('gras.sauce', 'Coulis de tomate', 30, 1.5, 5, 0.3, [], a='sauce tomate passata')
F('gras.sauce', 'Olives vertes', 145, 1, 3.8, 15, [('olive|olives', 4, 's')], a='olive')
F('gras.sauce', 'Sauce soja', 60, 8, 5, 0, [('càs', 15, 'd'), ('càc', 5, 'd')])

# ================================================================ AJOUTS 2026.10.08-10
# ---- oeufs et laitiers (suite)
F('lait.yaourt', 'Fromage blanc 20 %', 105, 7.5, 4, 6.5, [('pot|pots', 100, 'd')], a='faisselle')
F('lait.yaourt', 'Yaourt aux fruits', 90, 3.5, 14, 2, [('pot|pots', 125, 'd')], a='yogourt yoghourt sucre')
F('lait.yaourt', 'Yaourt au soja nature', 45, 4, 2.5, 2, [('pot|pots', 125, 'd')], a='yogourt vegetal alpro')
F('lait.yaourt', 'Petit-suisse', 130, 8, 3.5, 9, [('petit-suisse|petits-suisses', 60, 's')], a='petit suisse fromage frais')
F('lait.yaourt', 'Kéfir nature', 55, 3.5, 4.5, 2.5, [('verre|verres', 200, 'd')], ml=True, a='kefir lait fermente')
F('lait.fromage', 'Ricotta', 150, 11, 3, 10, [], a='fromage frais')
F('lait.fromage', 'Mascarpone', 400, 4.5, 4, 41, [('càs', 20, 'd')], a='fromage')
F('lait.fromage', 'Gouda', 355, 25, 2, 27, [('tranche|tranches', 20, 'd')], a='fromage')
F('lait.fromage', 'Roquefort', 370, 20, 1, 32, [], a='fromage bleu')
F('lait.fromage', 'Fromage de chèvre (bûche)', 270, 18, 1, 22, [('tranche|tranches', 25, 'd')], a='chevre fromage')
F('lait.fromage', 'Reblochon', 330, 21, 0.5, 27, [('part|parts', 40, 'd')], a='fromage')
F('lait.fromage', 'Fromage à raclette', 330, 22, 1, 27, [('tranche|tranches', 25, 'd')], a='fromage')
F('lait.fromage', 'Fromage fondu en portion', 230, 10, 6, 18, [('portion|portions', 17, 'd')], a='vache qui rit fromage tartiner')
F('lait.creme', 'Crème liquide 30 %', 300, 2.2, 3, 30, [('càs', 15, 'd')], a='creme entiere cuisine')

# ---- viandes (suite)
F('vpo.viande', 'Poulet rôti (viande et peau)', 215, 25, 0, 13, [], a='volaille')
F('vpo.charcut', 'Jambon de dinde', 100, 19, 1, 2, [('tranche|tranches', 40, 'd')], a='charcuterie volaille')
F('vpo.charcut', 'Blanc de poulet en tranches', 105, 21, 1, 2, [('tranche|tranches', 25, 'd')], a='charcuterie volaille')
F('vpo.viande', 'Rôti de porc cuit', 170, 28, 0, 6, [], a='viande')
F('vpo.viande', 'Côte de porc cuite', 220, 27, 0, 12, [], a='viande')
F('vpo.viande', 'Côtelette d’agneau cuite', 250, 25, 0, 17, [], a='viande')
F('vpo.viande', 'Gigot d’agneau cuit', 215, 28, 0, 11, [], a='viande')
F('vpo.viande', 'Bavette de bœuf crue', 140, 21, 0, 6, [], a='boeuf steak viande')
F('vpo.viande', 'Entrecôte cuite', 250, 27, 0, 15, [], a='boeuf steak viande')
F('vpo.viande', 'Rosbif', 140, 24, 0, 4.5, [('tranche|tranches', 40, 'd')], a='boeuf viande')
F('vpo.viande', 'Steak haché 15 % cuit', 255, 26, 0, 17, [], a='boeuf hache viande')
F('vpo.viande', 'Magret de canard cuit', 240, 27, 0, 14, [], a='viande')
F('vpo.charcut', 'Saucisson sec', 410, 28, 1, 33, [('tranche|tranches', 5, 'd')], a='charcuterie porc')
F('vpo.charcut', 'Chorizo', 450, 24, 2, 38, [('tranche|tranches', 5, 'd')], a='charcuterie porc')
F('vpo.charcut', 'Pâté de campagne', 270, 13, 2, 23, [('tranche|tranches', 30, 'd')], a='charcuterie porc')
F('vpo.charcut', 'Merguez', 290, 15, 1, 25, [('merguez|merguez', 80, 's')], a='saucisse')

# ---- poissons (suite)
F('vpo.poisson', 'Truite cuite', 170, 26, 0, 7, [], a='poisson')
F('vpo.poisson', 'Maquereau cuit', 260, 24, 0, 18, [], a='poisson')
F('vpo.poisson', 'Sardines fraîches cuites', 210, 25, 0, 12, [], a='poisson')
F('vpo.poisson', 'Dorade cuite', 130, 22, 0, 4.5, [], a='poisson')
F('vpo.poisson', 'Bar cuit', 125, 24, 0, 3, [], a='poisson loup')
F('vpo.poisson', 'Merlu cuit', 100, 21, 0, 1.5, [], a='poisson colin')
F('vpo.poisson', 'Églefin (haddock) cuit', 95, 21, 0, 0.8, [], a='poisson eglefin')
F('vpo.poisson', 'Thon frais cuit', 140, 29, 0, 2.5, [], a='poisson steak')
F('vpo.poisson', 'Crevettes crues', 75, 16, 0.5, 0.8, [], a='fruits de mer')
F('vpo.poisson', 'Moules cuites', 85, 12, 3.5, 2.2, [], a='fruits de mer')
F('vpo.poisson', 'Calamars', 90, 16, 2, 1.5, [], a='fruits de mer encornet')
F('vpo.poisson', 'Noix de Saint-Jacques', 85, 17, 2, 0.8, [], a='fruits de mer coquille')

# ---- feculents (suite)
F('fec.pates', 'Gnocchis cuits', 160, 4, 32, 1.5, [PORTION], a='gnocchi pomme de terre')
F('fec.pates', 'Nouilles de riz cuites', 110, 1.8, 25, 0.2, [PORTION], a='vermicelles asiatique')
F('fec.pates', 'Nouilles chinoises cuites', 125, 4, 25, 1, [PORTION], a='asiatique')
F('fec.pates', 'Polenta cuite', 70, 1.6, 15, 0.4, [PORTION], a='semoule mais')
F('fec.pates', 'Blé cuit (type Ebly)', 125, 4.5, 25, 0.6, [PORTION], a='ble ebly')
F('fec.pain', 'Pain aux céréales', 255, 10, 42, 4.5, [('tranche|tranches', 35, 'd')], a='pain complet graines')
F('fec.pain', 'Pain de seigle', 240, 8, 48, 1.5, [('tranche|tranches', 35, 'd')])
F('fec.pain', 'Pain pita', 270, 9, 55, 1.2, [('pain pita|pains pita', 60, 's')], a='pita')
F('fec.cereales', 'Muesli sans sucre ajouté', 350, 10, 62, 6, [('bol|bols', 50, 'd')], a='cereales petit dejeuner')
F('fec.pates', 'Farine de blé', 350, 10, 73, 1.3, [('càs', 10, 'd')])
F('fec.legumineuses', 'Flageolets cuits (égouttés)', 105, 7, 15, 0.6, [], a='legumineuse haricot conserve')
F('fec.legumineuses', 'Pois cassés cuits', 115, 8, 18, 0.5, [PORTION], a='legumineuse')
F('fec.legumineuses', 'Seitan', 120, 24, 4, 1.5, [], a='gluten vegetal proteine')
F('fec.legumineuses', 'Protéines de soja texturées (sèches)', 330, 50, 30, 1, [], a='pvt vegetal proteine')

# ---- legumes (suite)
F('fl.legumes', 'Ail', 130, 6.4, 24, 0.5, [('gousse d’ail|gousses d’ail', 5, 's')])
F('fl.legumes', 'Poireau', 30, 2, 5, 0.3, [])
F('fl.legumes', 'Choux de Bruxelles', 40, 4, 4, 0.5, [], a='chou')
F('fl.legumes', 'Kale (chou frisé)', 50, 4, 6, 1, [], a='chou')
F('fl.legumes', 'Céleri branche', 15, 0.7, 2, 0.2, [])
F('fl.legumes', 'Fenouil', 25, 1.2, 4, 0.2, [])
F('fl.legumes', 'Navet', 25, 1, 5, 0.2, [])
F('fl.legumes', 'Endive', 17, 0.9, 3, 0.1, [])
F('fl.legumes', 'Artichaut', 50, 3, 9, 0.3, [])
F('fl.legumes', 'Germes de soja', 30, 3, 3, 0.5, [])
F('fec.legumineuses', 'Édamame', 125, 11, 9, 5, [], a='soja edamames')
F('fl.legumes', 'Ratatouille', 60, 1.3, 6, 3.5, [PORTION], a='legumes cuisines')
F('plat.soupe', 'Soupe de légumes', 35, 1, 5, 1, [('bol|bols', 300, 'd')], a='potage veloute')
F('fl.legumes', 'Poêlée de légumes surgelée', 40, 2, 6, 0.7, [PORTION], a='legumes surgeles')
F('gras.sauce', 'Cornichons', 15, 0.8, 2, 0.3, [('cornichon|cornichons', 10, 's')])

# ---- fruits (suite)
F('fl.fruits', 'Pamplemousse', 40, 0.7, 8.5, 0.1, [('pamplemousse|pamplemousses', 250, 's')])
F('fl.fruits', 'Prune', 45, 0.7, 10, 0.2, [('prune|prunes', 40, 's')])
F('fl.fruits', 'Figue fraîche', 70, 0.8, 16, 0.3, [('figue|figues', 50, 's')])
F('fl.fruits', 'Mûres', 45, 1.4, 5, 0.5, [], a='mure')
F('fl.fruits', 'Pêches au sirop', 65, 0.5, 15, 0.1, [])
F('fl.fruits', 'Salade de fruits frais', 50, 0.7, 11, 0.2, [('bol|bols', 150, 'd')])
F('fl.secs', 'Pruneaux', 240, 2.5, 55, 0.5, [('pruneau|pruneaux', 10, 's')], a='fruit sec')
F('fl.secs', 'Abricots secs', 240, 3.5, 50, 0.5, [('abricot sec|abricots secs', 8, 's')], a='fruit sec')
F('fl.secs', 'Figues sèches', 250, 3.3, 57, 1, [('figue sèche|figues sèches', 20, 's')], a='fruit sec')
F('boisson.jus', 'Smoothie aux fruits', 55, 0.6, 12, 0.2, [('verre|verres', 250, 'd')], ml=True, a='boisson jus')

# ---- gras, noix, sucre (suite)
F('gras.huile', 'Huile de tournesol', 900, 0, 0, 100, [('càs', 13, 'd'), ('càc', 5, 'd')], a='matiere grasse')
F('lait.creme', 'Margarine', 720, 0.2, 0.5, 80, [('càc', 5, 'd')], a='matiere grasse')
F('sucre.tartiner', 'Beurre d’amande', 620, 21, 7, 55, [('càs', 16, 'd'), ('càc', 5, 'd')], a='amande puree')
F('sucre.tartiner', 'Purée de sésame (tahini)', 600, 17, 12, 53, [('càs', 15, 'd')], a='tahin')
F('fl.secs', 'Graines de lin', 500, 18, 2, 42, [('càs', 10, 'd')], a='graine')
F('fl.secs', 'Graines de courge', 560, 30, 5, 46, [('càs', 10, 'd')], a='graine')
F('fl.secs', 'Graines de tournesol', 580, 21, 17, 48, [('càs', 10, 'd')], a='graine')
F('fl.secs', 'Graines de sésame', 580, 18, 12, 51, [('càs', 10, 'd')], a='graine')
F('fl.secs', 'Noix de pécan', 690, 9, 4, 72, [('poignée|poignées', 25, 'd')], a='pecan oleagineux fruits a coque')
F('fl.secs', 'Noix du Brésil', 660, 14, 4, 66, [('noix du Brésil|noix du Brésil', 5, 's')], a='bresil oleagineux fruits a coque')
F('fl.secs', 'Noix de coco râpée', 600, 6, 7, 60, [('càs', 8, 'd')], a='coco')
F('lait.creme', 'Lait de coco', 190, 1.8, 3, 19, [('càs', 15, 'd')], ml=True, a='creme coco')
F('sucre.choco', 'Cacao maigre en poudre', 320, 20, 10, 12, [('càc', 4, 'd'), ('càs', 8, 'd')], a='chocolat poudre non sucre')
F('sucre.choco', 'Chocolat noir 85 %', 600, 11, 17, 50, [('carré|carrés', 8, 'd')], a='carre')
F('gras.sauce', 'Vinaigrette', 450, 0.5, 3, 48, [('càs', 15, 'd')], a='sauce assaisonnement')
F('gras.huile', 'Vinaigre balsamique', 90, 0.5, 17, 0, [('càs', 15, 'd')])
F('gras.sauce', 'Pesto', 480, 5, 4, 48, [('càs', 15, 'd')], a='sauce basilic')
F('gras.sauce', 'Sauce barbecue', 130, 1, 30, 0.5, [('càs', 17, 'd')], a='bbq sauce')
F('sucre.sucre', 'Sirop d’agave', 310, 0, 76, 0, [('càs', 20, 'd')])
F('lait.lait', 'Lait concentré sucré', 330, 8, 55, 9, [('càs', 20, 'd')])

# ---- boissons (suite)
F('boisson.jus', 'Thé glacé', 30, 0, 7.5, 0, [('canette|canettes', 330, 'd')], ml=True, a='the ice tea')
F('boisson.jus', 'Boisson énergisante', 45, 0, 11, 0, [('canette|canettes', 250, 'd')], ml=True, a='energy drink red bull')
F('boisson.jus', 'Jus de tomate', 17, 0.8, 3.5, 0.1, [('verre|verres', 200, 'd')], ml=True)
F('boisson.jus', 'Limonade', 38, 0, 9.5, 0, [('verre|verres', 200, 'd')], ml=True, a='soda')
F('boisson.alcool', 'Cidre', 45, 0.1, 4, 0, [('verre|verres', 200, 'd')], ml=True, a='alcool')
F('boisson.alcool', 'Champagne ou vin pétillant', 80, 0.3, 1.5, 0, [('coupe|coupes', 100, 'd')], ml=True, a='alcool')
F('boisson.alcool', 'Alcool fort (vodka, whisky…)', 230, 0, 0, 0, [('dose|doses', 40, 'd')], ml=True, a='alcool rhum gin spiritueux')
F('boisson.cafe', 'Chocolat chaud (lait et cacao sucré)', 75, 3.2, 11, 2.2, [('tasse|tasses', 200, 'd')], ml=True, a='cacao boisson')
F('boisson.jus', 'Eau de coco', 20, 0.2, 4, 0.2, [('verre|verres', 200, 'd')], ml=True)
F('sport.boisson', 'Boisson protéinée prête à boire', 60, 10, 4, 0.8, [('bouteille|bouteilles', 330, 'd')], ml=True, a='shake proteine')

# ---- autres (suite)
F('sport.whey', 'Protéine végétale en poudre', 380, 75, 8, 6, [('dose|doses', 30, 'd')], a='pois proteine poudre shaker vegan')
F('sport.whey', 'Caséine en poudre', 370, 78, 4, 2, [('dose|doses', 30, 'd')], a='proteine poudre shaker')
F('sport.barre', 'Barre protéinée', 360, 30, 30, 12, [('barre|barres', 55, 's')], a='proteine snack')
F('snack.barre', 'Barre de céréales', 400, 6, 68, 12, [('barre|barres', 25, 's')], a='snack')
F('snack.chips', 'Chips nature', 540, 6, 50, 35, [('poignée|poignées', 30, 'd')], a='snack aperitif')
F('snack.chips', 'Pop-corn nature', 380, 12, 65, 5, [('bol|bols', 20, 'd')], a='mais snack')
F('gras.sauce', 'Olives noires', 115, 0.8, 6, 11, [('olive|olives', 4, 's')], a='olive')
F('gras.sauce', 'Sauce tomate cuisinée', 55, 1.5, 8, 2, [], a='sauce pates bolognaise')

# ---- plats et en-cas (nouvelle categorie)
F('plat.pizza', 'Pizza margherita', 250, 10, 31, 9, [('part|parts', 120, 'd')], a='pizza fromage tomate')
F('plat.sandwich', 'Cheeseburger', 250, 13, 27, 10, [('cheeseburger|cheeseburgers', 120, 's')], a='hamburger burger fast food')
F('plat.sandwich', 'Kebab (sandwich)', 220, 11, 20, 10, [('kebab|kebabs', 350, 's')], a='sandwich grec fast food')
F('fl.legumes', 'Frites (friteuse)', 310, 3.5, 38, 15, [PORTION], a='pommes de terre fast food')
F('fl.legumes', 'Frites au four', 160, 2.5, 25, 5.5, [PORTION], a='pommes de terre maison')
F('fec.pain', 'Croissant', 410, 8, 45, 22, [('croissant|croissants', 50, 's')], a='viennoiserie boulangerie')
F('fec.pain', 'Pain au chocolat', 420, 7, 46, 23, [('pain au chocolat|pains au chocolat', 60, 's')], a='viennoiserie boulangerie')
F('fec.pain', 'Brioche', 380, 8, 50, 16, [('tranche|tranches', 35, 'd')], a='viennoiserie')
F('sucre.biscuit', 'Crêpe nature', 215, 6.5, 28, 8.5, [('crêpe|crêpes', 50, 's')], a='crepe sucree')
F('sucre.biscuit', 'Pancakes', 220, 6.5, 30, 8, [('pancake|pancakes', 45, 's')], a='petit dejeuner')
F('sucre.biscuit', 'Gaufre', 330, 6, 45, 14, [('gaufre|gaufres', 75, 's')])
F('plat.plat', 'Galette complète (jambon, œuf, fromage)', 190, 10, 16, 9.5, [('galette|galettes', 200, 's')], a='crepe sarrasin bretonne')
F('plat.sandwich', 'Croque-monsieur', 280, 14, 22, 15, [('croque-monsieur|croque-monsieur', 150, 's')], a='sandwich jambon fromage')
F('plat.sandwich', 'Sandwich jambon-beurre', 270, 11, 32, 10, [('sandwich|sandwichs', 200, 's')], a='baguette')
F('plat.pizza', 'Quiche lorraine', 270, 10, 17, 18, [('part|parts', 150, 'd')], a='tarte salee')
F('plat.plat', 'Lasagnes bolognaise', 150, 8, 13, 7, [('portion|portions', 300, 'd')], a='lasagne pates')
F('plat.plat', 'Spaghetti bolognaise', 130, 6.5, 16, 4, [('assiette|assiettes', 350, 'd')], a='pates viande hachee')
F('plat.plat', 'Pâtes carbonara', 190, 8, 21, 8, [('assiette|assiettes', 300, 'd')], a='pates lardons creme')
F('plat.plat', 'Hachis parmentier', 130, 7, 12, 6, [('portion|portions', 300, 'd')], a='gratin viande pomme de terre')
F('plat.plat', 'Gratin dauphinois', 130, 3, 12, 8, [('portion|portions', 250, 'd')], a='pomme de terre creme')
F('fl.legumes', 'Purée de pommes de terre', 90, 2, 14, 3, [('portion|portions', 200, 'd')], a='puree patate')
F('plat.plat', 'Riz cantonais', 150, 5, 22, 4.5, [('portion|portions', 300, 'd')], a='riz asiatique')
F('plat.plat', 'Chili con carne', 120, 9, 10, 5, [('portion|portions', 300, 'd')], a='haricots rouges boeuf')
F('plat.plat', 'Ravioli à la sauce tomate (boîte)', 95, 3.5, 13, 3, [('boîte|boîtes', 400, 'd')], a='conserve pates')
F('plat.plat', 'Sushi (maki, nigiri)', 150, 6, 28, 1.5, [('sushi|sushis', 25, 's')], a='maki californien japonais')
F('plat.plat', 'Nems au porc', 240, 9, 25, 11, [('nem|nems', 80, 's')], a='asiatique')
F('plat.plat', 'Taboulé', 150, 3, 20, 6, [('portion|portions', 150, 'd')], a='salade semoule')
F('plat.plat', 'Cordon bleu', 240, 15, 14, 14, [('cordon bleu|cordons bleus', 120, 's')], a='poulet pane jambon fromage')
F('plat.plat', 'Nuggets de poulet', 260, 14, 17, 15, [('nugget|nuggets', 18, 's')], a='poulet pane')
F('plat.plat', 'Filet de poisson pané', 200, 12, 18, 9, [('filet|filets', 100, 'd')], a='poisson pane')
F('sucre.dessert', 'Tarte aux pommes', 230, 2.5, 33, 10, [('part|parts', 120, 'd')], a='dessert patisserie')
F('sucre.dessert', 'Mousse au chocolat', 215, 5, 22, 12, [('pot|pots', 70, 'd')], a='dessert')
F('sucre.dessert', 'Riz au lait', 120, 3.2, 20, 3, [('pot|pots', 125, 'd')], a='dessert')
F('sucre.dessert', 'Crème dessert au chocolat', 120, 3.5, 19, 3.5, [('pot|pots', 125, 'd')], a='dessert danette')
F('sucre.biscuit', 'Biscuits secs (petit-beurre)', 440, 7, 74, 12, [('biscuit|biscuits', 8, 's')], a='gateau sec')
F('sucre.biscuit', 'Madeleine', 420, 6, 50, 22, [('madeleine|madeleines', 25, 's')], a='gateau')
F('sucre.biscuit', 'Cookie', 480, 5, 65, 22, [('cookie|cookies', 40, 's')], a='biscuit gateau')
F('sucre.choco', 'Barre chocolatée', 490, 6, 62, 24, [('barre|barres', 45, 's')], a='snack mars snickers')
F('sucre.dessert', 'Glace vanille', 200, 3.5, 24, 10, [('boule|boules', 50, 'd')], a='creme glacee dessert')

# ---------------------------------------------------------------- controles et ecriture
def slug(s):
    s = s.lower().replace('œ', 'oe').replace('’', ' ')
    s = unicodedata.normalize('NFD', s)
    s = ''.join(ch for ch in s if unicodedata.category(ch) != 'Mn')
    return re.sub(r'[^a-z0-9]+', '-', s).strip('-')

out, seen = [], set()
warn = []
for r in TABLE:
    i = slug(r['n'])
    assert i not in seen, 'doublon : ' + r['n']
    seen.add(i)
    kc = 4 * r['p'] + 4 * r['c'] + 9 * r['f']
    if r['k'] > 40 and abs(kc - r['k']) / r['k'] > 0.12:
        warn.append((r['n'], r['k'], round(kc)))
    assert r['cat'] in VALID, ('rangement inconnu', r['n'], r['cat'])
    assert 0 <= r['k'] <= 900 and r['p'] + r['c'] + r['f'] <= 101, r['n']
    for lab, g, mode in r['u']:
        assert g > 0 and mode in ('s', 'd'), (r['n'], lab)
    o = dict(id=i, cat=r['cat'], n=r['n'], k=r['k'], p=r['p'], c=r['c'], f=r['f'])
    if r['ml']: o['ml'] = 1
    if r['u']: o['u'] = [[lab, g, 1 if m == 's' else 0] for lab, g, m in r['u']]
    if r['top']: o['top'] = r['top']
    if r['a']: o['a'] = r['a']
    out.append(o)

here = os.path.dirname(os.path.abspath(__file__))
dest = os.path.join(here, '..', 'src', 'js2e.js')
with open(dest, 'w', encoding='utf8') as fh:
    fh.write("/* ===== ALIMENTS DE BASE - fichier genere par tools/gen_aliments.py, ne pas editer a la main ===== */\n")
    fh.write("/* Valeurs moyennes pour 100 g (100 ml pour les boissons) : indicatives. */\n")
    fh.write("const FOODS=" + json.dumps(out, ensure_ascii=False, separators=(',', ':')) + ";\n")

cats = {}
for o in out: cats[o['cat']] = cats.get(o['cat'], 0) + 1
print(len(out), 'aliments ecrits dans', os.path.normpath(dest))
print(' ', ', '.join('%s %d' % kv for kv in sorted(cats.items())))
print('courants :', [o['n'] for o in sorted([o for o in out if o.get('top')], key=lambda x: x['top'])])
print('ecarts kcal / macros > 12 % (fibres, alcool, valeurs de table) :')
for w in warn: print('  ', w)
